apiVersion: v1
kind: Pod
metadata:
  name: systester1
spec:
  containers:
  - name: systester1
    image: ubuntu:20.04
    command: 
    args:
    - apt update && apt upgrade -y && apt install -y git vim ssh gcc
    volumeMounts:
    - name: ftrace
      mountPath: /data/shared
    - name : syscaller
      mountPath: /program
  volumes:
  - name : ftrace
    hostPath:
      path: /sys/kernel/debug/
      type: Directory
  - name : syscaller
    hostPath:
      path: /home/kw1
      type : Directory
      